### ISSUE TITLE
Mattermost sends a notification to a user if someone joins Arbor with the same username

### ISSUE THREAD

**Issue by BitiTiger** [arborchat/arbormost#2]
**Summary**
If someone joins an Arbor server with a username that matches a username on Mattermost, Mattermost will send a notification saying the Arbormost bot mentioned them.

**Example**
`user1` is a registered username on Mattermost. Arbormost is being used to link an Arbor server to a Mattermost channel. If someone joins the Arbor server using `user1` or `@user1`, the person who registered `user1` on Mattermost will receive a notification saying they were mentioned by the Arbormost bot.

**Behavior**
- If someone joins an Arbor server with an `@` in front of their username and the username is registered on Mattermost, then Mattermost will send a notification to the user saying they were mentioned by the Arbormost bot.
- If someone joins an Arbor server with a username that is registered on Mattermost, then Mattermost will send a notification to the user saying they were mentioned by the Arbormost bot.
- If someone joins an Arbor server with a username that is not registered on Mattermost, then Mattermost will treat the username as plain text.
- If someone joins an Arbor server with an `@` in front of their username and the username is not registered on Mattermost, then Mattermost will treat the username as plain text.

**Issue**
This functionality can be used to troll users on a Mattermost server if someone on Arbor sets their username to match the person they want to annoy.

**Possible Fix**
Have Arbormost encapsulate the Arbor username inside ` `` ` since Mattermost does not trigger user mentions for preformatted text.
**Screenshot**
![git issue 2](https://user-images.githubusercontent.com/31015399/50525938-b2af5b00-0aac-11e9-89db-5b097005f88b.jpg)

**Comment by whereswaldon** [comment]
Resolved by #3
